name: flutter_components
description: A new Flutter project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speech: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  permission_handler: ^10.2.0
  plugin_platform_interface: ^2.0.2

  #Networking library
  m2p_flutter_base:
    git:
      url: git@bitbucket.org:abstractdevfactory/m2p_flutter_base.git
      ref: dev

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.components.flutter_components
        pluginClass: FlutterComponentsPlugin
      ios:
        pluginClass: FlutterComponentsPlugin
      linux:
        pluginClass: FlutterComponentsPlugin
      macos:
        pluginClass: FlutterComponentsPlugin
      windows:
        pluginClass: FlutterComponentsPluginCApi
      web:
        pluginClass: FlutterComponentsWeb
        fileName: flutter_components_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ilisarniq-Bold
      fonts:
        - asset: fonts/Ilisarniq-Bold.ttf

    - family: Ilisarniq-Italic
      fonts:
        - asset: fonts/Ilisarniq-Italic.ttf

    - family: Ilisarniq-Regular
      fonts:
        - asset: fonts/Ilisarniq-Regular.ttf

    - family: Ilisarniq-Medium
      fonts:
        - asset: fonts/Ilisarniq-Medium.ttf

    - family: Ilisarniq-MediumItalic
      fonts:
        - asset: fonts/Ilisarniq-MediumItalic.ttf

    - family: Ilisarniq-Light
      fonts:
        - asset: fonts/Ilisarniq-Light.ttf
